config/routes.rb
Gallery::Application.routes.draw do

  get "home/index"

  resources :users, :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "home#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :albums
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end
  
  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
  def index
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 # before_filter :require_no_user, :only => [:new, :create]
 # before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to(:root, :notice => 'Login successfull.')
    else
      render :action => :new
    end
  end

  def destroy
#    current_user_session.destroy
    @user_session = UserSession.find
    @user_session.destroy
    redirect_to(:root, :notice => 'Logout successfull.')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(:root, :notice => 'Registration successfull.')
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to(:root, :notice => 'Update successfull.')
    else
      render :action => 'edit'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h2>Hello, <% if current_user%><%= current_user.email%><%else%>guest<%end%>!</h2>

<p id="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="user_nav">
    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(:current) %> |
      <%= link_to "Logout", :logout %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
 

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h2  >Login</h2>

<%= render "user_sessions/form" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2 >Edit your info</h2>

<%= render 'users/form' %>

app/views/users/new.html.erb
<h2 id="">Register</h2>

<%= render "users/form" %>